### ISSUE TITLE
EISDIR Error

### ISSUE THREAD

**Issue by bizfreak22** [unblu/js-source-extractor#2]
Hello,

I am getting this error when running js-source-extractor

------

UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, mkdir '/'
    at Object.mkdirSync (fs.js:764:3)
    at /usr/local/lib/node_modules/js-source-extractor/dist/js-source-extractor.js:69:26
    at Array.reduce (<anonymous>)
    at mkdirPathSync (/usr/local/lib/node_modules/js-source-extractor/dist/js-source-extractor.js:66:26)
    at /usr/local/lib/node_modules/js-source-extractor/dist/js-source-extractor.js:204:21
    at /usr/local/lib/node_modules/js-source-extractor/dist/js-source-extractor.js:291:33
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/js-source-extractor/dist/js-source-extractor.js:266:46
    at /usr/local/lib/node_modules/js-source-extractor/node_modules/source-map/lib/source-map-consumer.js:78:16
(node:17892) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17892) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

-------

Any suggestions?

**Comment by truebden** [comment]
Hello bizfreak22,
can you please provide the options you are using?

**Comment by bizfreak22** [comment]
Hey, thanks for getting back so fast. 

First I tried js-source-extractor https://url.com/js/file.1b17f48199.js

Then I tried js-source-extractor https://url.com/js/file.1b17f48199.js --outDir temp/test2/

Same error message on both.

Just tried again .. same thing

![image](https://user-images.githubusercontent.com/33889841/64055743-7ca30900-cb5c-11e9-814d-030c412f3347.png)
